services:
  mariadb:
    container_name: mariadb-sql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 16102000
      MYSQL_USER: ram
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: social_network
    ports:
      - "3306:3306"
    networks:
      - spring-demo-kc
  keycloak:
    container_name: keycloak-security
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo-kc
    command:
      - "start-dev"
networks:
  spring-demo:
    driver: bridge

